#!/bin/bash

# The follwoing will attempt to install all needed packages to run Hyprland
# This is a quick and dirty script there are no error checking
# This script is meant to run on a clean fresh system
#
# Below is a list of the packages that would be installed
#
# hyprland: This is the Hyprland compositor
# kitty: This is the default terminal
# waybar: Waybar now has hyprland support
# swaybg: This is used to set a desktop background image
# swaylock-effects: This allows for the locking of the desktop its a fork that adds some editional visual effects
# wofi: This is an application launcher menu
# wlogout: This is a logout menu that allows for shutdown, reboot and sleep
# mako: This is a graphical notification daemon
# thunar: This is a graphical file manager
# ttf-jetbrains-mono-nerd: Som nerd fonts for icons and overall look
# noto-fonts-emoji: fonts needed by the weather script in the top bar
# polkit-gnome: needed to get superuser access on some graphical appliaction
# python-requests: needed for the weather module script to execute
# starship: allows to customize the shell prompt
# swappy: This is a screenshot editor tool
# grim: This is a screenshot tool it grabs images from a Wayland compositor
# slurp: This helps with screenshots, it selects a region in a Wayland compositor
# pamixer: This helps with audio settings such as volume
# brightnessctl: used to control monitor bright level
# gvfs: adds missing functionality to thunar such as automount usb drives
# bluez: the bluetooth service
# bluez-utils: command line utilities to interact with bluettoth devices
# lxappearance: used to set GTK theme
# xfce4-settings: set of tools for xfce, needed to set GTK theme
# dracula-gtk-theme: the Dracula theme, it fits the overall look and feel
# dracula-icons-git" set of icons to go with the Dracula theme
# xdg-desktop-portal-hyprland: xdg-desktop-portal backend for hyprland

#### Check for yay ####
ISYAY=/sbin/yay
if [ -f "$ISYAY" ]; then 
    echo -e "yay was located, moving on.\n"
    yay -Suy
else 
    echo -e "yay was not located, please install yay. Exiting script.\n"
    exit 
fi

### Disable wifi powersave mode ###
read -n1 -rep 'Would you like to disable wifi powersave? (y,n)' WIFI
if [[ $WIFI == "Y" || $WIFI == "y" ]]; then
    LOC="/etc/NetworkManager/conf.d/wifi-powersave.conf"
    echo -e "The following has been added to $LOC.\n"
    echo -e "[connection]\nwifi.powersave = 2" | sudo tee -a $LOC
    echo -e "\n"
    echo -e "Restarting NetworkManager service...\n"
    sudo systemctl restart NetworkManager
    sleep 3
fi

### Install all of the above pacakges ####
read -n1 -rep 'Would you like to install the basic packages? (y,n)' INST
if [[ $INST == "Y" || $INST == "y" ]]; then
    yay -S --noconfirm hyprland \
        swaybg swaylock-effects wofi wlogout mako thunar \
        ttf-jetbrains-mono-nerd \
        polkit-gnome python-requests \
        grim slurp pamixer brightnessctl gvfs \
        bluez bluez-utils lxappearance xfce4-settings \
        dracula-gtk-theme dracula-icons-git xdg-desktop-portal-hyprland \
        alacritty firefox

    # Setup Oh My Zsh and Powerlevel10k
    #echo -e "Setting up Oh My Zsh and Powerlevel10k...\n"
    # install zsh
    #sudo pacman -S --noconfirm zsh
    # install oh-my-zsh
    #sh -c "$(curl -fsSL https://raw.github.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"
    # install powerlevel10k
    #yay -S --noconfirm zsh-theme-powerlevel10k-git
    #echo 'source /usr/share/zsh-theme-powerlevel10k/powerlevel10k.zsh-theme' >>~/.zshrc

    # set zsh as default shell
    #chsh -s $(which zsh)
    # Login to Hyprland every time the system boots
    echo -e "Adding Hyprland to the .bashrc file...\n"
    echo -e "if [ -z \$DISPLAY ] && [ \$(tty) == /dev/tty1 ]; then\n    exec Hyprland\nfi" >>~/.bashrc

    # Start the bluetooth service
    echo -e "Starting the Bluetooth Service...\n"
    sudo systemctl enable --now bluetooth.service
    sleep 2

    # Clean out other portals
    echo -e "Cleaning out conflicting xdg portals...\n"
    yay -R --noconfirm xdg-desktop-portal-gnome xdg-desktop-portal-gtk
fi

read -n1 -rep 'Would you like to install the developer packages? (y,n)' DEV

if [[ $DEV == "Y" || $DEV == "y" ]]; then
    yay -S --noconfirm base-devel neovim nodejs npm lazygit
fi


### Copy Config Files ###
read -n1 -rep 'Would you like to copy config files? (y,n)' CFG
if [[ $CFG == "Y" || $CFG == "y" ]]; then
    echo -e "Copying config files...\n"
    cp -R hypr ~/.config/
    cp -R mako ~/.config/
    cp -R swaylock ~/.config/
    cp -R wofi ~/.config/

    mkdir -p ~/.config/alarritty
    cp alacritty.toml ~/.config/alacritty/

    # Set some files as exacutable 
    chmod +x ~/.config/hypr/xdg-portal-hyprland
fi

### Install Microsoft Surface ###
read -n1 -rep 'Would you like to install Microsoft Surface support? (y,n)' SUR
if [[ $SUR == "Y" || $SUR == "y" ]]; then
    echo -e "Import the keys used to sign packages...\n"
    curl -s https://raw.githubusercontent.com/linux-surface/linux-surface/master/pkg/keys/surface.asc | sudo pacman-key --add -

    echo -e "check and verify the fingerprint of the key...\n"
    sudo pacman-key --finger 56C464BAAC421453

    echo -e "Locally sign the key...\n"
    sudo pacman-key --lsign-key 56C464BAAC421453

    echo -e "adding the following to the end of /etc/pacman.conf"

    echo -e "\n[linux-surface]\nServer = https://pkg.surfacelinux.com/arch/" | sudo tee -a /etc/pacman.conf

    echo -e "Update the system...\n"
    sudo pacman -Suy

    echo -e "Installing the linux-surface kernel...\n"
    sudo pacman -S linux-surface linux-surface-headers iptsd
    # sudo pacman -S --noconfirm linux-surface linux-surface-headers linux-surface-docs linux-surface-firmware
fi

### Script is done ###
echo -e "Script had completed.\n"
echo -e "You can start Hyprland by typing Hyprland (note the capital H).\n"
read -n1 -rep 'Would you like to start Hyprland now? (y,n)' HYP
if [[ $HYP == "Y" || $HYP == "y" ]]; then
    exec Hyprland
else
    exit
fi
